/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LinhasIndexRouteImport } from './routes/linhas.index'
import { Route as LinhasLineIdRouteImport } from './routes/linhas.$lineId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhasIndexRoute = LinhasIndexRouteImport.update({
  id: '/linhas/',
  path: '/linhas/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhasLineIdRoute = LinhasLineIdRouteImport.update({
  id: '/linhas/$lineId',
  path: '/linhas/$lineId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/linhas/$lineId': typeof LinhasLineIdRoute
  '/linhas/': typeof LinhasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/linhas/$lineId': typeof LinhasLineIdRoute
  '/linhas': typeof LinhasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/linhas/$lineId': typeof LinhasLineIdRoute
  '/linhas/': typeof LinhasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/linhas/$lineId' | '/linhas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/linhas/$lineId' | '/linhas'
  id: '__root__' | '/' | '/linhas/$lineId' | '/linhas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LinhasLineIdRoute: typeof LinhasLineIdRoute
  LinhasIndexRoute: typeof LinhasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linhas/': {
      id: '/linhas/'
      path: '/linhas'
      fullPath: '/linhas/'
      preLoaderRoute: typeof LinhasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linhas/$lineId': {
      id: '/linhas/$lineId'
      path: '/linhas/$lineId'
      fullPath: '/linhas/$lineId'
      preLoaderRoute: typeof LinhasLineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinhasLineIdRoute: LinhasLineIdRoute,
  LinhasIndexRoute: LinhasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
